// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAjTIkTxlbi_ui9Rt0hs8-2EMQjGpbjA',
    appId: '1:969164142255:web:a725e5a2c71fe27b2e465a',
    messagingSenderId: '969164142255',
    projectId: 'newversion-cardgame-2025',
    authDomain: 'newversion-cardgame-2025.firebaseapp.com',
    storageBucket: 'newversion-cardgame-2025.firebasestorage.app',
    databaseURL: 'https://newversion-cardgame-2025.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKAjTIkTxlbi_ui9Rt0hs8-2EMQjGpbjA',
    appId: '1:969164142255:android:example',
    messagingSenderId: '969164142255',
    projectId: 'newversion-cardgame-2025',
    storageBucket: 'newversion-cardgame-2025.firebasestorage.app',
    databaseURL: 'https://newversion-cardgame-2025.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKAjTIkTxlbi_ui9Rt0hs8-2EMQjGpbjA',
    appId: '1:969164142255:ios:example',
    messagingSenderId: '969164142255',
    projectId: 'newversion-cardgame-2025',
    storageBucket: 'newversion-cardgame-2025.firebasestorage.app',
    databaseURL: 'https://newversion-cardgame-2025.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKAjTIkTxlbi_ui9Rt0hs8-2EMQjGpbjA',
    appId: '1:969164142255:macos:example',
    messagingSenderId: '969164142255',
    projectId: 'newversion-cardgame-2025',
    storageBucket: 'newversion-cardgame-2025.firebasestorage.app',
    databaseURL: 'https://newversion-cardgame-2025.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKAjTIkTxlbi_ui9Rt0hs8-2EMQjGpbjA',
    appId: '1:969164142255:windows:example',
    messagingSenderId: '969164142255',
    projectId: 'newversion-cardgame-2025',
    storageBucket: 'newversion-cardgame-2025.firebasestorage.app',
    databaseURL: 'https://newversion-cardgame-2025.firebaseio.com/',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAKAjTIkTxlbi_ui9Rt0hs8-2EMQjGpbjA',
    appId: '1:969164142255:linux:example',
    messagingSenderId: '969164142255',
    projectId: 'newversion-cardgame-2025',
    storageBucket: 'newversion-cardgame-2025.firebasestorage.app',
    databaseURL: 'https://newversion-cardgame-2025.firebaseio.com/',
  );
}
